######################## default configuration ####################
baseURL = "https://mustangccofc.com"
languageCode = "en-us"
title = "Mustang Car Club of Colorado"
theme="restaurant-hugo"
summaryLength = "7"
paginate = 4

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "css/slick.css"
  [[params.plugins.css]]
  URL = "css/font-awesome.min.css"
  [[params.plugins.css]]
  URL = "css/animate.min.css"
  [[params.plugins.css]]
  URL = "css/venobox.css"
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/responsive.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/jquery.min.js"
  [[params.plugins.js]]
  URL = "js/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "js/slick.min.js"
  [[params.plugins.js]]
  URL = "js/wow.min.js"
  [[params.plugins.js]]
  URL = "js/venobox.min.js"
  [[params.plugins.js]]
  URL = "js/main.js"

############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "Home"
  URL = "hero-area"
  weight = 1

  [[menu.main]]
  name = "About Us"
  URL = "about-us"
  weight = 2

  [[menu.main]]
  name = "Posts"
  URL = "blog"
  weight = 3

  [[menu.main]]
  name = "Membership"
  URL = "price"
  weight = 4

  [[menu.main]]
  name = "News"
  URL = "subscribe"
  weight = 5

  [[menu.main]]
  name = "Contact Us"
  URL = "contact-us"
  weight = 6


#################### default parameters ################################
[params]
# logo = "images/logo.png"
# meta data
author = "Themefisher"
description = "This is meta description"
# google analitycs ID
google_analitycs_id = "Your ID"
# copyright
copyright = "Copyright 2020 - All Rights Reserved. Mustang Car Club of Colorado"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

################################### Footer ############################
[params.footer]
enable = true
contactInfoTitle = "CONTACT <span>INFO</span> "
blogTitle = "LATEST <span>POSTS</span>"
galleryTitle = "PHOTO <span>STREAM</span>"
socialTitle = "Follow <span>US</span>"

############################ footer contact item
# [[params.footer.contactItem]]
# title="Telephone"
# icon = "fa fa-phone"
# content = "016742 323313"
#
# [[params.footer.contactItem]]
# title="Address"
# icon = "fa fa-map-marker"
# content = "2046 Blue Spruce Lane Laurel Canada"

[[params.footer.contactItem]]
title="E mail"
icon = "fa fa-envelope"
content = "mustangccofc@gmail.com"

######################### footer gallery
[[params.footer.gallery]]
image = "images/slider/P9281340.jpeg"

[[params.footer.gallery]]
image = "images/slider/P9281338.jpeg"

[[params.footer.gallery]]
image = "images/slider/P9281337.jpeg"

[[params.footer.gallery]]
image = "images/slider/P9281335.jpeg"

[[params.footer.gallery]]
image = "images/slider/P9281333.jpeg"

[[params.footer.gallery]]
image = "images/slider/IMG_5614.jpeg"

######################## Social Icon
[[params.footer.socialLink]]
icon = "facebook"
link = "https://mustangcarclubcolorado.github.io/"

#[[params.footer.socialLink]]
#icon = "twitter"
#link = "https://fb.com/themefisher"

#[[params.footer.socialLink]]
#icon = "instagram"
#link = "https://fb.com/themefisher"
